# Generated by Django 5.0.6 on 2024-06-19 09:02

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('office', models.CharField(max_length=50)),
                ('ato', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=50)),
                ('pen_number', models.CharField(max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('designation', models.CharField(choices=[('d', 'Driver'), ('c', 'Conductor')], max_length=2)),
                ('date_of_join', models.DateTimeField()),
                ('on_leave', models.BooleanField(default=False)),
                ('employee_depot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_depot', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
