# Generated by Django 5.0.6 on 2024-06-19 10:47

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_depot_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_depot',
        ),
        migrations.AddField(
            model_name='employee',
            name='depot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.depot'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='IN', unique=True),
        ),
    ]
