# Generated by Django 5.0.6 on 2024-06-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_employee_employee_depot_employee_depot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_join',
            field=models.DateField(),
        ),
    ]
