# Generated by Django 5.0.6 on 2024-06-19 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_employee_date_of_join'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='depot',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.DeleteModel(
            name='Depot',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
